name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches')|| startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build App
        run: |
          gradle app:assembleRelease
          gradle app:bundleRelease
      - name: Sign app APK
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: |
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > sekretess-keystore.jks
          $ANDROID_HOME/build-tools/35.0.1/apksigner sign --ks sekretess-keystore.jks --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD ~/work/consumer-android-app/consumer-android-app/app/build/outputs/apk/release/app-release-unsigned.apk
          mv ~/work/consumer-android-app/consumer-android-app/app/build/outputs/apk/release/app-release-unsigned.apk ~/work/consumer-android-app/consumer-android-app/app/build/outputs/apk/release/app-release-signed.apk
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}          
      - name: relase
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
