name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches')|| startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build App
        run: |
          gradle app:assembleRelease
          gradle app:bundleRelease
      - name: List Build APK directory
        run: |
          ls ~/work/consumer-android-app/consumer-android-app/app/build/outputs/apk/release/
      - name: Sign app APK
        run: |
          base64 -d << "$ANDROID_KEYSTORE_BASE64" > sekretess-keystore.jks
          $ANDROID_HOME/build-tools/35.0.1/apksigner sign --ks sekretess-keystore.jks --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD ~/work/consumer-android-app/consumer-android-app/app/build/outputs/apk/release/app-release-unsigned.apk
          ls
