name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches')|| startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build App
      run: gradle app:assembleRelease
    - name: Sign app APK
      uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        buildToolsVersion: 33.0.0
    - uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedFile}}
